[package]
name = "png"
version = "0.1.0"
authors = ["Dan Reeves <hey@danreev.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.2.0"
winit = "0.22.2"
winit_input_helper = "0.7.0"
